### PR TITLE
Delete old csprojs

### PR DESCRIPTION
**Pull request by valkyrienyanko**

### CODE REVIEW

**Comment by QueenOfSquiggles** [comment]
Hey thanks a ton for doing this! I was planning to get around to it, but it was pretty low priority. I'm currently away from my main development environment so I'll have to come back to this to fix "conflicts" and merge in.

**Review by QueenOfSquiggles — APPROVED** [review]
Approving the deletion of old csproj files. Hopefully this will let me merge it in

**Comment by valkyrienyanko** [comment]
I resolved the conflict in the .gitignore

**Comment by QueenOfSquiggles** [comment]
Just merged in. Thanks a ton for all your work!

**Pull request merged**
